### ISSUE TITLE
to-do: Review and clean up branches

### ISSUE THREAD

**Issue by CritiqalPete** [AmericaSCORESBayArea/AmericaScores-CoachApp#473]
it's time to prune the branches and stale code/references.
recommended procedure:

- [ ] select the branch
- [ ] do a diff with Master
- [ ] verify the changes are older than tip/current or not relevant (if unsure, open a review ticket noting the file/diff)
- [ ] delete the deprecated branch
